title: Roxanne Fequiere
email: roxanne.fequiere@gmail.com
description: >
  is a writer and editor living in New York.
baseurl: ""
url: "http://roxannefequiere.com"
twitter_username: roxannefequiere
instagram_username: roxannefequiere
linkedin_username: roxanne-fequiere-338bb413

# Build settings
markdown: kramdown
