---
title: Roxanne Fequiere
timezone: America/New_York
collections:
  pieces:
    title: Pieces
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pieces
  values:
    image: ''
    link: ''
    site: ''
email: roxanne.fequiere@gmail.com
description: 'is a writer and editor living in New York.

'
baseurl: 
url: http://roxannefequiere.com
twitter_username: roxannefequiere
instagram_username: roxannefequiere
linkedin_username: roxanne-fequiere-338bb413
markdown: kramdown
