---
title: Roxanne Fequiere
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: ''
    link: ''
    site: ''
email: roxanne.fequiere@gmail.com
description: is a writer and editor living in New York.
baseurl: 
url: http://roxannefequiere.com
twitter_username: roxannefequiere
instagram_username: roxannefequiere
linkedin_username: roxanne-fequiere-338bb413
markdown: kramdown
plugins:
- jekyll-redirect-from
