---
title: Roxanne Fequiere
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: roxanne.fequiere@gmail.com
description: 'is a writer and editor living in New York.

'
baseurl: ''
url: http://roxannefequiere.com
twitter_username: roxannefequiere
instagram_username: roxannefequiere
linkedin_username: roxanne-fequiere-338bb413
markdown: kramdown
gems:
- jekyll-redirect-from
